language: python
sudo: required
dist: trusty
matrix:
    include:
        - python: 3.5
          env: TENSORFLOW="0.10.0"
install:
    - source ci/install.sh
script:
    - bash ci/test.sh
notifications:
    email: false
